using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace Kepware.Api.Model
{
    /// <summary>
    /// Contains constants and static properties related to Kepware API properties.
    /// </summary>
    public partial class Properties
    {
        /// <summary>
        /// The description property key.
        /// </summary>
        public const string Description = "common.ALLTYPES_DESCRIPTION";
        /// <summary>
        /// The name property key.
        /// </summary>
        public const string Name = "common.ALLTYPES_NAME";
        /// <summary>
        /// The project ID property key.
        /// </summary>
        public const string ProjectId = "PROJECT_ID";
        

        /// <summary>
        /// Contains constants related to non-updatable properties.
        /// </summary>
        public static class NonUpdatable
        {
            /// <summary>
            /// The channel unique ID property key.
            /// </summary>
            public const string ChannelUniqueId = "servermain.CHANNEL_UNIQUE_ID";
            /// <summary>
            /// The device unique ID property key.
            /// </summary>
            public const string DeviceUniqueId = "servermain.DEVICE_UNIQUE_ID";

            /// <summary>
            /// Read-only property used to bind a Store and Forward datastore to a project.
            /// </summary>
            public const string ThingworxStoreAndForwardDatastoreId = "thingworxinterface.DATASTORE_ID";

            // DataLogger read-only property keys
            /// <summary>Data type of the batch ID item (read-only).</summary>
            public const string DataLoggerLogGroupBatchIdItemType = "datalogger.LOG_GROUP_BATCH_ID_ITEM_TYPE";
            /// <summary>Data type of a log item (read-only).</summary>
            public const string DataLoggerLogItemDataType = "datalogger.LOG_ITEM_DATA_TYPE";
            /// <summary>Data type of the trigger monitor item (read-only).</summary>
            public const string DataLoggerTriggerMonitorItemDataType = "datalogger.TRIGGER_MONITOR_ITEM_DATA_TYPE";
            /// <summary>Data type of the trigger start condition item (read-only).</summary>
            public const string DataLoggerTriggerConditionStartItemDataType = "datalogger.TRIGGER_CONDITION_START_ITEM_DATA_TYPE";
            /// <summary>Data type of the trigger stop condition item (read-only).</summary>
            public const string DataLoggerTriggerConditionStopItemDataType = "datalogger.TRIGGER_CONDITION_STOP_ITEM_DATA_TYPE";

            /// <summary>
            /// A set of non-updatable properties.
            /// </summary>
            public static readonly FrozenSet<string> AsHashSet = new HashSet<string>()
                {
                    ChannelUniqueId,
                    DeviceUniqueId,
                    ThingworxStoreAndForwardDatastoreId,
                    DataLoggerLogGroupBatchIdItemType,
                    DataLoggerLogItemDataType,
                    DataLoggerTriggerMonitorItemDataType,
                    DataLoggerTriggerConditionStartItemDataType,
                    DataLoggerTriggerConditionStopItemDataType,
                }.ToFrozenSet();
        }

        /// <summary>
        /// Contains constants related to non-serialized properties.
        /// </summary>
        public static class NonSerialized
        {
            /// <summary>
            /// The channel assignment property key.
            /// </summary>
            public const string ChannelAssignment = "servermain.DEVICE_CHANNEL_ASSIGNMENT";
            /// <summary>
            /// The total tag count in a tag group property key.
            /// </summary>
            public const string TagGrpTotalTagCount = "servermain.TAGGROUP_TOTAL_TAG_COUNT";
            /// <summary>
            /// The local tag count in a tag group property key. Used for tag groups within devices.
            /// </summary>
            public const string TagGrpTagCount = "servermain.TAGGROUP_LOCAL_TAG_COUNT";
            /// <summary>
            /// The static tag count in a channel property key.
            /// </summary>
            public const string ChannelStaticTagCount = "servermain.CHANNEL_STATIC_TAG_COUNT";
            /// <summary>
            /// The autogenerated tag group property key.
            /// </summary>
            public const string TagGroupAutogenerated = "servermain.TAGGROUP_AUTOGENERATED";
            /// <summary>
            /// The autogenerated tag property key.
            /// </summary>
            public const string TagAutogenerated = "servermain.TAG_AUTOGENERATED";
            /// <summary>
            /// The static tag count in a device property key.
            /// </summary>
            public const string DeviceStaticTagCount = "servermain.DEVICE_STATIC_TAG_COUNT";

            /// <summary>
            /// Count of tags identified in the project.
            /// </summary>
            public const string ProjectTagsDefined = "servermain.PROJECT_TAGS_DEFINED";

            /// <summary>
            /// Total number of tags configured under this agent (read-only).
            /// </summary>
            public const string ThisAgentTotal = "iot_gateway.AGENTTYPES_THIS_AGENT_TOTAL";

            /// <summary>
            /// Total number of tags configured under all agents (read-only).
            /// </summary>
            public const string AllAgentsTotal = "iot_gateway.AGENTTYPES_ALL_AGENTS_TOTAL";

            /// <summary>
            /// Maximum number of configured tags allowed by the license (read-only).
            /// </summary>
            public const string LicenseLimit = "iot_gateway.AGENTTYPES_LICENSE_LIMIT";

            /// <summary>
            /// A set of non-serialized properties.
            /// </summary>
            public static readonly FrozenSet<string> AsHashSet = new HashSet<string>()
                    {
                        ChannelAssignment,
                        TagGrpTotalTagCount,
                        TagGrpTagCount,
                        ChannelStaticTagCount,
                        TagGroupAutogenerated,
                        TagAutogenerated ,
                        DeviceStaticTagCount,
                        ProjectTagsDefined,
                    }.ToFrozenSet();
        }

        /// <summary>
        /// Don't allow instantiation of this class
        /// </summary>
        protected Properties()
        {
        }
    }
}
