namespace Kepware.Api.Model
{
    /// <summary>
    /// Represents a column mapping within a DataLogger log group.
    /// Column mappings are auto-generated by the server when log items are created and
    /// cannot be created or deleted via the API — only modified (PUT).
    /// </summary>
    [Endpoint("/config/v1/project/_datalogger/log_groups/{logGroupName}/column_mappings/{name}")]
    public class ColumnMapping : NamedEntity
    {
        /// <summary>Initializes a new instance of the <see cref="ColumnMapping"/> class.</summary>
        public ColumnMapping() { }

        /// <summary>Initializes a new instance of the <see cref="ColumnMapping"/> class with the specified name.</summary>
        /// <param name="name">The name of the column mapping.</param>
        public ColumnMapping(string name) : base(name) { }
    }
}
