name: .NET

on:
  
  push:
    branches: [ "master" ]
    paths:
      - 'Kepware.Api/**'
      - 'Kepware.Api.Sample/**'
      - 'KepwareSync.Service/**'
      - '.github/workflows/dotnet.yml' 
      - '!*.md' # Exclude markdown files
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Kepware.Api/**'
      - 'Kepware.Api.Sample/**'
      - 'KepwareSync.Service/**'
      - '.github/workflows/dotnet.yml'  
      - '!*.md' # Exclude markdown files

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, ubuntu]
    runs-on: ${{ matrix.platform }}-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
      - name: Use Release Drafter
        if: ${{ github.event_name != 'pull_request' }}
        id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.nbgv.outputs.SemVer2 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration release
      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' && matrix.platform == 'ubuntu' }}
        run: |
          dotnet nuget push ./Kepware.Api/bin/Release/*.nupkg \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      - name: dotnet publish
        run: dotnet publish KepwareSync.Service/Kepware.SyncService.csproj --configuration release -o publish /p:UseAppHost=true

      # Upload artifacts only for non-pull_request events
      - name: Upload Windows artifacts to release
        if: ${{ github.event_name != 'pull_request' && matrix.platform == 'windows' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.drafter.outputs.upload_url }}
          asset_path: publish/Kepware.SyncService.exe
          asset_name: Kepware.SyncService.win-x64.exe
          asset_content_type: application/octet-stream
      - name: Upload appsettings artifacts to release
        if: ${{ github.event_name != 'pull_request' && matrix.platform == 'windows' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.drafter.outputs.upload_url }}
          asset_path: publish/appsettings.json
          asset_name: appsettings.json
          asset_content_type: application/octet-stream

      - name: Upload Ubuntu artifacts to release
        if: ${{ github.event_name != 'pull_request' && matrix.platform == 'ubuntu' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.drafter.outputs.upload_url }}
          asset_path: publish/Kepware.SyncService
          asset_name: Kepware.SyncService.linux-x64
          asset_content_type: application/octet-stream